name: Matrix
on:
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(vars.MATRIX) }}
    steps:
      - run: echo ${{ secrets[format('{0}_USER', matrix.env)] }}
