name: Matrix
on:
  workflow_dispatch:
jobs:
  getMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.getMatrix.outputs.matrix }}
    steps:
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=${{ vars.MATRIX }}" >> $GITHUB_OUTPUT
     - run: echo "$GITHUB_OUTPUT"
  print:
    runs-on: ubuntu-latest
    needs: getMatrix
    strategy:
      matrix: ["var1", "var2"]
    steps:
     - run: echo ${{ matrix }}
